name: "ferrucyon iso"
on:
  push:
    tags:
      - '*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        nix_conf: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Build ferrucyon iso
      run: |
        nix build .#ferrucyon
        cp result/iso/nixos.iso ferrucyon.iso

    - name: Publish and release
      uses: softprops/action-gh-release@v1
      with:
        files: ferrucyon.iso
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
